version: "3.9"

services:
  db:
    # image: mysql
    # volumes:
    #   - mysql:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    #   - MYSQL_ROOT_HOST=%
    #   - MYSQL_DATABASE=${DB_DATABASE}
    #   - MYSQL_USER=${DB_USERNAME}
    #   - MYSQL_PASSWORD=${DB_PASSWORD}
    #   - MYSQL_ALLOW_EMPTY_PASSWORD=1
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: fly-dj4
    build:
      context: .
      dockerfile: Dockerfile_django
      args:
        - GROUPID=${GROUPID}
        - USERID=${USERID}
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:8000"
    restart: always
    env_file: .env
    depends_on:
      - db
  node:
    build:
      context: .
      dockerfile: Dockerfile_node
    ports:
      - "${DB_PORT}:5173"
    volumes:
      - .:/code
volumes:
  # mysql:
  #   driver: local
  postgres_data:
