# syntax=docker/dockerfile:1

FROM node

LABEL maintainer="Fernado Cruz"

RUN npm i -g npm@latest
COPY ./entry_point_node.sh /usr/local/bin/start-container

WORKDIR /code

EXPOSE 5173

ENTRYPOINT ["start-container"]